name: Android Tests

on: push

jobs:
  build:
    name: Gradle build pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew assembleNormalDebug


  junit:
    name: Unit tests
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Unit tests
        run: ./gradlew testNormalDebugUnitTest


  tests:
    name: Instrumentation tests
    needs: [build]
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run all instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: pixel
          target: google_apis
          script: ./gradlew connectedNormalDebugAndroidTest --stacktrace
