name: Android CI

on: [push]

jobs:
  build:
    name: Gradle build pass

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build


  tests:
    name: Instrumentation tests
    needs: build

    runs-on: macOS-10.14

    steps:
      - uses: actions/checkout@v1

      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.3

      - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.3
        with:
          cmd: ./gradlew integrationTest
          api: 25
          tag: google_apis
          abi: x86
